// Generated by CoffeeScript 1.10.0
(function() {
  var Hapi, host, port, random, server, value;

  Hapi = require('hapi');

  server = new Hapi.Server();

  random = require("random-js")();

  port = 3000;

  host = 'localhost';

  server.connection({
    host: host,
    port: port
  });

  server.start(function(err) {
    if (err == null) {
      return console.log("Server started listening on localhost:3000...");
    }
  });

  server.register(require('inert'), function(err) {
    if (err) {
      throw err;
      return server.route;
    }
  });

  ({
    method: 'GET',
    path: '/',
    handler: function(request, reply) {
      reply('Hello, world!');
    }
  });

  server.route({
    method: 'GET',
    path: '/',
    handler: function(request, reply) {
      return reply.file('./public/index.html');
    }
  });

  value = random.integer(1, 100);

  console.log(value);


  /*
    server.route({
          method: 'GET',
          path: '/hello',
          handler: function (request, reply) {
              reply.file('./public/hello.html');
          }
      });
  });
   */

}).call(this);
